# Exported from Render on 2025-05-27T10:33:36Z
services:
  - type: web
    name: ws-data-layer
    runtime: node
    repo: https://github.com/Zeeohn/WordSanctuarySystemsNew
    plan: free
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: CENTRAL_SYSTEMS_FRONTEND_URL
        sync: false
      - key: ROOT_USER_PASSWORD
        sync: false
      - key: ROOT_USER_EMAIL
        sync: false
      - key: POSTGRES_CONN_URI
        sync: false
      - key: MONGODB_CONN_URI
        sync: false
    region: frankfurt
    buildCommand: npm run deploy
    startCommand: npm run start
    autoDeployTrigger: commit
    rootDir: data-layer-microservice/server

  - type: web
    name: ws-central-systems
    runtime: node
    repo: https://github.com/Zeeohn/WordSanctuarySystemsNew
    plan: free
    envVars:
      - key: JWT_SIGN_SECRET
        sync: false
      - key: ROOT_USER_EMAIL
        sync: false
      - key: NODE_ENV
        value: production
      - key: DATA_LAYER_SYSTEMS_BASE_API
        sync: false
      - key: DATA_LAYER_KPI_ENDPOINT
        sync: false
      - key: DATA_LAYER_POSTGRESS_ENDPOINT
        sync: false
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeployTrigger: commit
    rootDir: central-systems/backend/server
version: "1"
